-- Supabase/PostgreSQL schema

CREATE TABLE IF NOT EXISTS gifts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL DEFAULT 'Geral',
  name text NOT NULL,
  image_url text,
  reserved boolean NOT NULL DEFAULT false,
  reserved_by text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS gift_reservations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gift_id bigint NOT NULL REFERENCES gifts(id) ON DELETE CASCADE,
  guest_name text NOT NULL,
  reserved_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guest_name text NOT NULL,
  message text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS timeline_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date text NOT NULL,
  title text NOT NULL,
  description text,
  image_url text,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_gifts_reserved ON gifts(reserved);
CREATE INDEX IF NOT EXISTS idx_comments_created_at ON comments(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gift_reservations_gift_id ON gift_reservations(gift_id);
CREATE INDEX IF NOT EXISTS idx_timeline_display_order ON timeline_events(display_order);
